[package]
name = "emu-nes"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
emu-core.workspace = true
bitflags.workspace = true
thiserror.workspace = true
