[package]
name = "midi2nes"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "midi2nes"
path = "src/main.rs"

[dependencies]
midly = "0.5"
clap = { workspace = true }
anyhow = { workspace = true }
